### ISSUE TITLE
[FEATURE]: Be able to run view on all calls

### ISSUE THREAD

**Issue by JoeGandy** [joachimdalen/AzureDevOpsExtensions#5]
**Is your feature request related to a problem? Please describe.**
At the moment the check action is only available, this is good for checking whats tags are there.
Itd be useful for some of our builds to be able to cleanly pull PR descriptions, PR status, PR comments?

**Describe the solution you'd like**
Add a new action 'view' to each option, just pulling back whats in the data

**Additional context**
Some should be easy, descriptions, tags etc. But comments may be trickier due to changing content

**Comment by joachimdalen** [comment]
Hi!

Well, I think this would only be relevant for pull request descriptions and tags. Both comments and statuses contains a bit more of a complex data structure that would be hard to expose in a good way. This could of course just be exposed directly as the JSON content returned, but then I think a custom script would be more appropriate and not an extension for extracting the needed data. Very large response objects here could also be difficult to expose correctly.

- Example of PR status structure: [Examples](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/statuses/list?view=azure-devops-rest-5.1#examples)
- Example of PR thread structure: [Examples](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/pull%20request%20threads/list?view=azure-devops-rest-5.1#examples)

In the current extension state, I can add this for tags/labels and description, but I will need to do some more research and thinking before considering it for statuses and comments.

**Comment by JoeGandy** [comment]
Yeah I agree, we only needed it for the description initially, not sure if would get used much beyond tags/description

**Comment by joachimdalen** [comment]
I will take a look at it over the weekend. The extension already fetches the description and processes it, so will only need to expose this out. Will probably be done the same way as tag check.

**Comment by joachimdalen** [comment]
Hi, 

I added a new action, `view`, to `PullRequestDescription` that can now be used to load the description of the pull request into a variable. You can find this in `PullRequestUtils@0.5.0`  -  `PullRequestDescription@0.2.0`.

```yaml
steps:
  - task: PullRequestDescription@0
    name: setDescriptionVariable
    inputs:
      action: 'view'
      outputVariable: 'PullRequest.DescriptionContent'
      isOutput: true
      stripIdentifiers: false
  - script: echo $(setDescriptionVariable.PullRequest.DescriptionContent)
```

`PullRequestDescription` uses some interal modifiers to know where to append content to. If you wish to remove these before setting the variable, set `stripIdentifiers` to true. See extension page for information.
