### ISSUE TITLE
[BUG] [Pull Request Utils]: Unable to create a comment with "Resolved" status

### ISSUE THREAD

**Issue by badsyntax** [joachimdalen/AzureDevOpsExtensions#6]
**Describe the bug**

I think the title describes the bug adequality.

**Agent Type**
- [x] Hosted
- [ ] Self Hosted

**Agent OS**
- [ ] Windows
- [ ] Linux
- [x] OSX

```yaml
- task: PullRequestComments@0
  inputs:
    content: 'Some content here'
    action: create
    status: Resolved
    commentId: $(Build.BuildId)
```
